### ISSUE TITLE
Unable to locate package python-pip Ubuntu 20.04

### ISSUE THREAD

**Issue by Limaomao821** [Martins3/My-Linux-config#10]
When execute ```checkhealth``` in nvim, there might be some error with python2-related problems.
According to :help provider-python, we need to execute ```python2 -m pip install --user --upgrade pynvim```.
However, python2 on ubuntu 20.04 no longer supports installation of python-pip by ```apt-get install```(you still could use ```apt-get install python3-pip```).
You could solve the problem using the link below.
https://stackoverflow.com/questions/61981156/unable-to-locate-package-python-pip-ubuntu-20-04

**Comment by Martins3** [comment]
If it works, just ignore the complaints. If not, show me your `checkhealth` result.
