### ISSUE TITLE
File tree icon displayed incorrectly

### ISSUE THREAD

**Issue by popoQWQ** [Martins3/My-Linux-Config#107]
As shown in the picture
![Snipaste_2022-12-25_02-28-13](https://user-images.githubusercontent.com/119121003/209447590-d62409e3-8f03-416e-82a1-c6c311991f9a.png)

**Comment by Martins3** [comment]
What's your terminal? Maybe you forget to install nerdfont [^1]

[^1]: https://martins3.github.io/My-Linux-Config/docs/nvim.html#%E5%AE%89%E8%A3%85-nerdfonts

**Comment by Martins3** [comment]
Is the problem fixed?
