### ISSUE TITLE
怎么复制vim中的内容到系统的粘贴版

### ISSUE THREAD

**Issue by Korov** [Martins3/My-Linux-config#11]
- **Describe the bug**
A clear and concise description of the bug.
- **ccls --version**
- ccls version <unknown>
clang version 11.0.1

- **nvim --version**
- nvim --version    
NVIM v0.4.4

- **checkhealth screenshot**

![image](https://user-images.githubusercontent.com/45894441/105622762-fe30c080-5e4e-11eb-8b5c-09a06856c6ce.png)

**Comment by Martins3** [comment]
> , y 和 , p 实现复制粘贴

**Comment by Korov** [comment]
用了 `,y` 下面显示   `14 lines yanked into "+`  但是在外面用`ctrl + v`没有获取到复制的内容

**Comment by Martins3** [comment]
那么你可以使用 " + y 来拷贝到系统的剪切板吗 ?

**Comment by Korov** [comment]
也不行，我用的archlinux，是哪里没配好吗？

**Comment by Martins3** [comment]
1. 你是在 mac 上使用的吗 ?
2. 你是在远程服务器上使用的吗 ?

**Comment by Martins3** [comment]
> 也不行，我用的archlinux，是哪里没配好吗？
我以前就是在 archlinux 上使用的，是没有问题的。从 checkhealth 上看，配置的很正常。

**Comment by Korov** [comment]
我知道了是archlinux的问题
https://vim.fandom.com/wiki/Accessing_the_system_clipboard

**Comment by Martins3** [comment]
所以，解决了?

**Comment by Korov** [comment]
> 所以，解决了?

sudo pacman -S wl-clipboard    用这个就可以复制了xclip还是不行，除非重新编译vim或者用gvim

**Comment by xcaptain** [comment]
为啥在编辑器内复制直接 y 就可以，要复制到系统剪贴板就得 `, y` 感觉不够一致

**Comment by Martins3** [comment]
你可以看看 vim 里面的 register 这个概念。在 vim 中间，不只是有一个剪切板，使用 `y` 和 `,` `y` 对应两个剪切板，第一个是 vim 内部的，第二个是系统的。
这种做法的好处是，在 vim 内部粘贴的时候，不会污染系统的剪切板。
![DeepinScreenshot_select-area_20210305111559](https://user-images.githubusercontent.com/16731244/110062437-34dded00-7da4-11eb-9096-2e7b768f4c3c.png)
