### ISSUE TITLE
Hi when I start the neovim, it can show below picture.

### ISSUE THREAD

**Issue by Nigelwz** [Martins3/My-Linux-Config#113]
- [ ] **Describe the bug**
A clear and concise description for the bug.
- [ ] **ccls --version**
- [ ] **nvim --version**
- [ ] **Operating System**
- [ ] **CocInfo**
- [ ] **checkhealth screenshot**
![image](https://user-images.githubusercontent.com/18673071/217891508-2ebf8ebf-927f-4ee3-9b00-ba64e363cfa8.png)

**Comment by Martins3** [comment]
run `:PackerInstall` to install plugins, then the warnings shall disappear.
