### ISSUE TITLE
Is there any plan to migrate packer.nvim to lazy.nvim?

### ISSUE THREAD

**Issue by IfanTsai** [Martins3/My-Linux-Config#124]
从 packer.nvim 的仓库来看已经有段时间没有更新维护了，同时了解到 packer 作者也在切换到 lazy.nvim 了，现在很多人也都在使用 lazy.nvim 了，有任何计划迁移下插件管理工具到 lazy 吗？

ref issue: [https://github.com/wbthomason/packer.nvim/issues/1229](https://github.com/wbthomason/packer.nvim/issues/1229)

**Comment by Martins3** [comment]
有计划，前段时间把 coc.nvim 替换掉了，最近准备着手将 packer.nvim 替换掉。
