### ISSUE TITLE
英文提示补全的功能没有了吗？

### ISSUE THREAD

**Issue by marryton007** [Martins3/My-Linux-Config#129]
打扰一下，最新配置里没有英文提示补全的插件吗？我觉得那个功能很好用的。

**Comment by Martins3** [comment]
你说的是应该是这个功能吧 https://github.com/neoclide/coc-sources/blob/master/packages/word/10k.txt

**Comment by Martins3** [comment]
因为从 coc 切换到 native lsp，这个功能暂时没有了，我周末研究下怎么移植下

**Comment by marryton007** [comment]
对，就是这个，辛苦大佬。

**Comment by Martins3** [comment]
这个功能我终于知道怎么实现了，预计这几天进入到 master

**Comment by marryton007** [comment]
大佬辛苦，还记得这事呢，我都差不多忘了。
