### ISSUE TITLE
安装复现问题咨询

### ISSUE THREAD

**Issue by flyingTan** [Martins3/My-Linux-config#13]
你好，很高兴你能开源你的项目，但是我在安装时候遇到一些问题，方便加一下个人微信吗？

**Comment by Martins3** [comment]
很高兴这个项目对你有所帮助，你可以将你遇到的问题详情粘贴到这 issue 上，这样我就可以帮你解决了, 解决的过程也可以帮助其他人参考

**Comment by flyingTan** [comment]
非常感谢回复，由于我之前用原生VIM+GDB 和 IDE比较多，所以直接上手 SpaceVim 所以问题比较多。目前我问题是 defx file icon 显示不对。
![image](https://user-images.githubusercontent.com/31298946/112299524-d8029200-8cd2-11eb-933f-dfe404385643.png)

`init.toml` 如下：
![image](https://user-images.githubusercontent.com/31298946/112299807-231ca500-8cd3-11eb-854f-e5123cb8641d.png)

所以麻烦解答一下，应如何正确使用 defx，非常感谢～

**Comment by Martins3** [comment]
在我的配置中间存在这一行用于打开 file icon:
https://github.com/Martins3/My-Linux-config/blob/7e56e17977f3f2b98843f94620578d2a4678303b/autoload/myspacevim.vim#L28

此外，需要 iterm2 支持图标，你可以了解一下：
https://github.com/ryanoasis/nerd-fonts

**Comment by Martins3** [comment]
![Web capture_24-3-2021_20122_user-images githubusercontent com](https://user-images.githubusercontent.com/16731244/112307463-eef9b200-8cdb-11eb-99cd-d83a181e1d96.jpeg)
上面的圈出的位置，需要 iterm2 的字体设置为一种 nerd font, 下面的需要打开这个选项

**Comment by flyingTan** [comment]
非常感谢耐心回复，但是我还是遇到一个问题：
+ MAC iterm2 配置如下：

![image](https://user-images.githubusercontent.com/31298946/112329305-0cd21180-8cf2-11eb-8436-babfd6395f4e.png)

+ 远端fu wu qi服务器配置如下：
![image](https://user-images.githubusercontent.com/31298946/112329915-8ff36780-8cf2-11eb-94a0-f6cec87de2c1.png)

+ 结果1:
![image](https://user-images.githubusercontent.com/31298946/112329709-63d7e680-8cf2-11eb-8f43-59063988adf7.png)

疑问：貌似部分正常，但是 defx 目录图标显示还是有些问题～不知是什么情况，麻烦解答一下，感谢～

**Comment by Martins3** [comment]
![Web capture_24-3-2021_20122_user-images githubusercontent com](https://user-images.githubusercontent.com/16731244/112307463-eef9b200-8cdb-11eb-99cd-d83a181e1d96.jpeg)
上面圈出来位置的应该修复了吧

**Comment by flyingTan** [comment]
目前是这样：
![image](https://user-images.githubusercontent.com/31298946/112335541-4b1dff80-8cf7-11eb-88c4-aa6291c87bd9.png)
但是我想知道如何实现如下效果麻烦告知下，这样辨识度高一些：
![image](https://user-images.githubusercontent.com/31298946/112335864-8fa99b00-8cf7-11eb-8b34-f46f9dc4c4c9.png)

**Comment by Martins3** [comment]
我知道, 但是，按道理来说，你这个应该是没有问题的

**Comment by Martins3** [comment]
你把 checkhealth 的结果贴出来

**Comment by flyingTan** [comment]
![image](https://user-images.githubusercontent.com/31298946/112337441-e1065a00-8cf8-11eb-8ce7-319f200c2a97.png)
![image](https://user-images.githubusercontent.com/31298946/112337483-e82d6800-8cf8-11eb-8f77-9da1aaa0564a.png)
以上是有 error 和 warm 的地方～

**Comment by Martins3** [comment]
SPDebugInfo 的结果也贴出来看看

**Comment by Martins3** [comment]
neovim 版本看看

**Comment by flyingTan** [comment]
![image](https://user-images.githubusercontent.com/31298946/112338303-a94be200-8cf9-11eb-9f2f-3a251e002f80.png)
![image](https://user-images.githubusercontent.com/31298946/112338667-f0d26e00-8cf9-11eb-826e-7aae22686569.png)

**Comment by Martins3** [comment]
SPDebugInfo 得要的结果应该是这个吧

![image](https://user-images.githubusercontent.com/16731244/112339101-558dc880-8cfa-11eb-815b-bb789bba31e9.png)

顺便说一下，tmux 的警告可以参考我的 tmux 配置 https://github.com/Martins3/My-Linux-config/blob/master/scripts/tmux.conf

**Comment by flyingTan** [comment]
![Uploading image.png…]()

**Comment by flyingTan** [comment]
![image](https://user-images.githubusercontent.com/31298946/112340068-2deb3000-8cfb-11eb-804b-fbfbc070aea8.png)

**Comment by Martins3** [comment]
这个图片似乎上传不了，你可以粘贴一下文本

**Comment by Martins3** [comment]
粘贴全部的文本

**Comment by flyingTan** [comment]
auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['liuchengxu/vista.vim', {'name': 'liuchengxu/vista.vim', 'overwrite': 1}], ['lilydjwg/colorizer', {'repo': 'lilydjwg/colorizer', 'on_cmd': ['ColorHighlight', 'ColorToggle'], 'merged':
 0, 'overwrite': 1}]]
  data_dir = '/home/tanfeiyang/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'left'
filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/tanfeiyang/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'coveragepy.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
 terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'

**Comment by Martins3** [comment]
似乎问题找到了，你的配置中间是 enable_vimfiler_filetypeicon = 0

**Comment by Martins3** [comment]
看来这个选项并没有生效

**Comment by flyingTan** [comment]
enen ~~ 我并没该这些配置，那我应如何配置，感谢～

**Comment by Martins3** [comment]
这是我的配置你的截图看，你设置了 ` let g:spacevim_enable_vimfiler_filetypeicon = 1 `，看来是没有生效啊

```
enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 1
```

**Comment by flyingTan** [comment]
我再研究一下，非常感谢耐心回复 ～

**Comment by Martins3** [comment]
要不将这个配置放到这个中间 ?
```viml
func! myspacevim#after() abort
endf
```

**Comment by Martins3** [comment]
或者你把你现在的配置仓库的地址给我，我看看在我的机器上的效果

**Comment by flyingTan** [comment]
![image](https://user-images.githubusercontent.com/31298946/112436764-15bdf400-8d81-11eb-81a1-34799b639f13.png)
抱歉昨天太晚没及时回复，我今天重新装了 spacevim，却出现新的问题，可以帮忙解答一下吗？

**Comment by Martins3** [comment]
你的改动是什么总得给我说一下吧，你这只给一个报错信息，谁也不可能知道是什么原因啊。

**Comment by flyingTan** [comment]
并没改动如何东西：
+ spacevim repo:  v1.6.0
![image](https://user-images.githubusercontent.com/31298946/112438641-18b9e400-8d83-11eb-9b43-9a0f52e4e18a.png)
+ neovim: v0.4.4
![image](https://user-images.githubusercontent.com/31298946/112438736-35eeb280-8d83-11eb-8845-aa054cacf677.png)
+ 安装显示正常: 但输入 nvim 就提示
![image](https://user-images.githubusercontent.com/31298946/112438850-5b7bbc00-8d83-11eb-8b35-486907a692a5.png)
+ 最后显示如下：
![image](https://user-images.githubusercontent.com/31298946/112438978-8534e300-8d83-11eb-83cb-ce2ba20ec87b.png)


PS: 如果我 checkout 到 V1.5.0 没错误提示～～

**Comment by flyingTan** [comment]
DEBUG INFO 如下：
auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/tanfeiyang/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/tanfeiyang/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'open-browser.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'

**Comment by Martins3** [comment]
你只是重装了一下吗? 在 .Spacevim.d 下面还有自己的额外的配置吗 ?

**Comment by Martins3** [comment]
如果有，你可以吧这些配置放到 github 上，然后地址发给我看看。

**Comment by flyingTan** [comment]
+ 1. 安装问题找到了：（直接卸载貌似 cache 还有缓存，需要手动删除）
![image](https://user-images.githubusercontent.com/31298946/112443041-718b7b80-8d87-11eb-8e9d-c62e3de8f117.png)

这样应该不会出问题：
```
curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
rm -rf ~/.SpaceVimi* 
rm -rf ~/.cache/SpaceVim
```

+  2. 删除重新安装如下：
![image](https://user-images.githubusercontent.com/31298946/112443178-9bdd3900-8d87-11eb-9a99-416b0a594a51.png)

+ 3. 正确显示 icon
![image](https://user-images.githubusercontent.com/31298946/112445584-422a3e00-8d8a-11eb-9dd4-e027e6a91ff6.png)


最后，非常非常感谢耐心回复～

**Comment by Martins3** [comment]
great
