### ISSUE TITLE
Need one way to quickly switch buffer to left/right buffer by keyboard.

### ISSUE THREAD

**Issue by huangpufan** [Martins3/My-Linux-Config#130]
- What's your suggestion?
I need a convinient way to switch current buffer to the left buffer or right buffer.

- Why is better?
I found that you map the "tab" as the switcher of opened windows.
However switching files by keyboard is the most common need of daily uses.
And I tested "alter+left/right","command + left/right",they are all useless.

But as a rookie of neovim, I dont know how to set the keymap of this function.
Would you add this function or tell me how to set it.

- How to implement your ideas?

**Comment by huangpufan** [comment]
I noticed that leader + number can switch buffer.But sometimes we only want to switch to left/right buffer.
Would it be supported?

**Comment by Martins3** [comment]
vim default keymap, `<C-w> l` can jump to the right window.

https://github.com/Martins3/My-Linux-Config/blob/1d6fd5b9842ace2ad0f637ceba985ccdc15a845b/nvim/lua/usr/which-key.lua#L143

type `c L` to jump to the right window, this can be configured to `c l`

https://github.com/Martins3/My-Linux-Config/blob/1d6fd5b9842ace2ad0f637ceba985ccdc15a845b/nvim/lua/usr/which-key.lua#L51

jump to window 1 with `<Space> 1`

if you need `ctrl l` to jump to the right window, this is possible, I can also add the keybinding.

**Comment by huangpufan** [comment]
> vim default keymap, `<C-w> l` can jump to the right window.
> 
> https://github.com/Martins3/My-Linux-Config/blob/1d6fd5b9842ace2ad0f637ceba985ccdc15a845b/nvim/lua/usr/which-key.lua#L143
> 
> type `c L` to jump to the right window, this can be configured to `c l`
> 
> https://github.com/Martins3/My-Linux-Config/blob/1d6fd5b9842ace2ad0f637ceba985ccdc15a845b/nvim/lua/usr/which-key.lua#L51
> 
> jump to window 1 with `<Space> 1`
> 
> if you need `ctrl l` to jump to the right window, this is possible, I can also add the keybinding.

Thanks to your reply. My expression lead to misunderstanding.
My meaning is that just in single window, I want to switch to the left buffer or right buffer. 
I noticed that using leader + number can do this. 
And after searching, I found "bp" can switch to left buffer,"bn" can switch to right buffer.
I will map it to <alter left> / <alter right>.
