### ISSUE TITLE
kitty terminal 中文问题

### ISSUE THREAD

**Issue by wqk151** [Martins3/My-Linux-Config#134]
您好，最近使用kitty终端，使用`GLFW_IM_MODULE=ibus kitty`这种方式启动kitty可以输入中文。我把`GLFW_IM_MODULE=ibus`加入到环境变量中，配置在`/etc/profile`文件，输入法用的是ibus，ubuntu20.04自带的输入法，echo查看GLFW_IM_MODULE变量也是生效了的，单独启动kitty就无法使用输入法，请问您这边有什么设置建议吗？

**Comment by Martins3** [comment]
我晚点有时间研究下，这个问题我也遇到过

**Comment by Martins3** [comment]
说实话，这个问题，也一直困扰我，我的 nixos 上 wezterm 也是偶尔中文输入法可以，而 kitty 总是可以。感觉你的解决思路是没有问题，但是具体最后为什么，可能还需要搜索，调试，分析。也许和我一样，面对这种问题，将就着过。

**Comment by wqk151** [comment]
恩，好的，感谢！
目前只能将就着用，要么换arch，要么估计等ubuntu支持wayland，感觉目前ubuntu22的会有很多兼容性问题，暂时不敢用。

**Comment by Martins3** [comment]
兼容性问题还好吧，当然看你平常主要用程序了。
