### ISSUE TITLE
wsl2中启动报错

### ISSUE THREAD

**Issue by yhl41001** [Martins3/My-Linux-Config#135]
您好，我在wsl2中安装了nvim的配置，启动nvim的时候报错：
Error detected while processing /mnt/d/ubuntu/.dotfiles/nvim/init.vim:
line   43:
Failed to load/parse file
Press ENTER or type command to continue

我看了一下init.vim中的43行代码：
" 加载 lua 配置
lua require 'usr'
请问这个是什么问题？

**Comment by Martins3** [comment]
有截图吗？ 按了 Enter  之后的报错是什么？

**Comment by yhl41001** [comment]
@Martins3 我已经找到原因了，是需要安装im-select，wsl中比Ubuntu要麻烦一些，多谢啦！

**Comment by yhl41001** [comment]
@Martins3 另外您这个配置有建群吗，我发现用起来问题比较多，有不少问题需要问一下的。主要是很多快捷键不熟，还有就是我的tree是显示在右边的，搜索框也是上下排列的，不是左右排列的，不知道是不是因为wsl的原因。

**Comment by Martins3** [comment]
> @Martins3 另外您这个配置有建群吗，我发现用起来问题比较多，有不少问题需要问一下的。

如果有问题可以提 issue，如果哪里你感觉不对的可以提交 PR，建群没必要了。

> 主要是很多快捷键不熟

这个没办法了，但是多用几天就会熟悉的。

> 还有就是我的tree是显示在右边的，搜索框也是上下排列的，不是左右排列的，不知道是不是因为wsl的原因。

不是，应该是配置变化了，对应的截图没更新。对于新手来说，这个确实容易误解，你可以把这些有问题的图片标记下，下次我一并修改下（当然你也可以修改）。把图片上传到 github issue 中，然后在 md  中应用图片。

**Comment by yhl41001** [comment]
@Martins3 好的，我现在用的wsl可能和Ubuntu也不一样，等我用我Ubuntu电脑试一下吧，多谢！
