### ISSUE TITLE
Typo error in Doc

### ISSUE THREAD

**Issue by Shipley1105** [Martins3/My-Linux-Config#136]
- What's your suggestion?
- Why is better?
- How to implement your ideas?
https://github.com/Martins3/My-Linux-Config/blob/master/docs/nvim.md#%E5%85%A5%E9%97%A8-vim 
如果完全没有基础，建议使用 openvim 打牢基础之后，然后就直接将 vim 用于实战中间，因为这些快捷键都是肌肉记忆，无非多熟悉一下而已。当你知道 hikl **<<<<<< should be hjkl**之类的操作之后，之后可以 使用 vim check sheet 来强化补充一下，不要指望一次全部背下来，也没有必要全部记住，一次学几个，学最能提高你工作效率的那几个。

https://github.com/Martins3/My-Linux-Config/blob/master/docs/nvim.md#%E5%85%A5%E9%97%A8-vim

如果想要跳转到函数头，在 vim 中使用默认提供 [[``m](https://stackoverflow.com/questions/2109503/how-to-jump-to-the-beginning-of-the-current-function-body-in-vim)，但是这是根据词法规则实现的，要么跳转到第一个匹配的 { ，要么跳转到最外层的 { ，因此 对于文件的格式有要求，但是如何 <<<<< ”如果“     使用上 [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects)，这个问题就不存在了，你总是可以跳转到函数的开始位置。

**Comment by Martins3** [comment]
多谢，可以提一个 PR 修改下吗？
