### ISSUE TITLE
The abnormal display of absolute path

### ISSUE THREAD

**Issue by Shipley1105** [Martins3/My-Linux-Config#139]
![issue](https://github.com/Martins3/My-Linux-Config/assets/80968554/5b0361e4-b126-4acf-86c3-8ff4bb0ea84a)

**Comment by Martins3** [comment]
https://github.com/Martins3/My-Linux-Config/blob/master/docs/nvim.md#%E5%AE%89%E8%A3%85-nerdfonts may be useful.

**Comment by Martins3** [comment]
1. What's the terminal emulator?
2. `,` `j` and show me the screenshot, this is what I expected
![image](https://github.com/Martins3/My-Linux-Config/assets/16731244/4fe0cff3-64e1-45a7-ac03-a38444ec546b)

**Comment by Martins3** [comment]
can you make a pull request to fix this issue, thanks :)
