### ISSUE TITLE
nvim module 'rsync_nvim' not found

### ISSUE THREAD

**Issue by qZhang88** [Martins3/My-Linux-Config#142]
clone了你的nvim，已经安装cargo和rsync，打开nvim还是有下面的问题

Failed to source `/Users/zq/.local/share/nvim/lazy/rsync.nvim/plugin/rsync.lua`
vim/_editor.lua:0: /Users/zq/.config/nvim/init.vim[43]..nvim_exec2() called at /Users/zq/.config/nvim/init.vim:43../Users/zq/.local/share/nvim/lazy/rsync.nvim/plugin/rsync.lua: Vim(source):E5113: Error while callin
g lua chunk: .../.local/share/nvim/lazy/rsync.nvim/lua/rsync/project.lua:4: module 'rsync_nvim' not found:
^Ino field package.preload['rsync_nvim']
cache_loader: module rsync_nvim not found
cache_loader_lib: module rsync_nvim not found
^Ino file './rsync_nvim.lua'
^Ino file '/opt/homebrew/share/luajit-2.1.0-beta3/rsync_nvim.lua'
^Ino file '/usr/local/share/lua/5.1/rsync_nvim.lua'
^Ino file '/usr/local/share/lua/5.1/rsync_nvim/init.lua'
^Ino file '/opt/homebrew/share/lua/5.1/rsync_nvim.lua'
^Ino file '/opt/homebrew/share/lua/5.1/rsync_nvim/init.lua'
^Ino file './rsync_nvim.so'
^Ino file '/usr/local/lib/lua/5.1/rsync_nvim.so'
^Ino file '/opt/homebrew/lib/lua/5.1/rsync_nvim.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
^I[C]: in function 'require'
^I.../.local/share/nvim/lazy/rsync.nvim/lua/rsync/project.lua:4: in main chunk
^I[C]: in function 'require'
^I.../zq/.local/share/nvim/lazy/rsync.nvim/lua/rsync/init.lua:5: in main chunk
^I[C]: in function 'require'
^I...rs/zq/.local/share/nvim/lazy/rsync.nvim/plugin/rsync.lua:2: in main chunk
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua: in function 'cmd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:467: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:466>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:110: in function 'try'
^I...
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:393: in function 'packadd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:328: in function '_load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:184: in function 'load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:116: in function 'startup'
^I...rs/zq/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:85: in function 'setup'
^I/Users/zq/.config/nvim/lua/usr/lazy.lua:14: in main chunk
^I[C]: in function 'require'
^I/Users/zq/.config/nvim/lua/usr/init.lua:2: in main chunk
^I[C]: in function 'require'
^I[string ":lua"]:1: in main chunk
# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - lua/usr/lazy.lua:14
  - lua/usr/init.lua:2
  - lua/:1

**Comment by Martins3** [comment]
进入到 ~/.local/share/nvim/lazy/rsync.nvim 中执行下 make ，我看看

**Comment by Martins3** [comment]
@qZhang88  问题解决了吗？
