### ISSUE TITLE
wezterm 内容不能够居中

### ISSUE THREAD

**Issue by looopig** [Martins3/My-Linux-Config#144]
# 环境

wayland：Hyprland
OS：NixOS

# 问题

wezterm 不论设置怎么设置边框填充，终端中的内容都不能够居中显示（内容周围填充并不均匀），想请问下有什么办法解决么，或者说现在还是不能够实现这个

在 wezterm issues 中看到过相关问题，可是我貌似没有解决这个问题

**Comment by Martins3** [comment]
可以截图看看吗？不过这个问题指望我解决，恐怕有点难，我尝试过 Nixos 下的 Hyprland，但是发现 Microsoft edge 不能正常显示，很快就放弃了。

**Comment by looopig** [comment]
台式机已经是默认 kde 了，只是笔记本不带鼠标用 kde 还是有点慢，现在 hyprland 能用就行，也就是没事折腾折腾，折腾过一年也就知道没必要折腾了，我都打算用 kde 脚本平铺了

**Comment by Martins3** [comment]
这个 issue 先关闭，有其他问题也欢迎讨论，尤其是 QEMU, Linux 之类的。
