### ISSUE TITLE
Why not use mason to manage lsp

### ISSUE THREAD

**Issue by IfanTsai** [Martins3/My-Linux-Config#145]
`lua/usr/lsp/mason.lua` 中屏蔽了 setup 逻辑，不解为何不使用 mason 来管理 lsp，现在的 lsp server 都要一个一个手动安装，使用 mason 来安装不更优雅吗

**Comment by Martins3** [comment]
mason 怎么用还没研究清楚，这个 lsp 的代码都是从 nvim from scratch 中抄过来的。
更觉我的理解，mason 是管理 lsp server 安装，但是我使用的 nixos 本来就可以处理各种包的安装[^1]。
不过应该不会冲突，我周末研究下 mason 怎么使用。

[^1]:https://github.com/Martins3/My-Linux-Config/blob/master/nixpkgs/home/cli.nix

**Comment by Martins3** [comment]
我先用两天试试，如果没问题就并入主线

**Comment by IfanTsai** [comment]
mason 提供的 UI 应该还是很方便的，到时候可以比较下原来的方式分享 mason 带来的感受
