### ISSUE TITLE
LSP[ccls]: Error NO_RESULT_CALLBACK_FOUND

### ISSUE THREAD

**Issue by yhl41001** [Martins3/My-Linux-Config#147]
LSP[ccls]: Error NO_RESULT_CALLBACK_FOUND: {                                                                                                                       
  error = {
    code = -32603,
    message = "failed to index /home/src/dof_wrapper.cpp"
  },
  id = 1,
  jsonrpc = "2.0"
}
您好，为用您这个配置，遇到的问题安装lazy的时候会报错，rsync_nvim.so的问题，然后打开文件也会报错，lsp的代码无法索引。

**Comment by Martins3** [comment]
issue 是有 template 的，你可以按照 template 提供更多的信息吗? 

rsync_nvim.so 的报错你可以先将这一行删除 https://github.com/Martins3/My-Linux-Config/blob/1d3c5379dea8ca6dc9b14ad1b8e69a0a273388b7/nvim/lua/usr/init.lua#L28 

lsp 先用一个只有一个文件的项目，给我看看报错。

**Comment by yhl41001** [comment]
问题有点多也有点复杂，好像是clang或者clangd版本不对，我换了一个其他的配置，能正常安装插件了，但是还是有非常多的文件报错，就是红色下划线的文件找不到问题，但代码编译是能过的。也生成了json文件。

**Comment by Martins3** [comment]
你这些描述都太模糊了，否则我没有办法在我的环境中复现
