### ISSUE TITLE
method textDocument/completion is not supported by any of the servers registered for the current buffer

### ISSUE THREAD

**Issue by yhl41001** [Martins3/My-Linux-Config#148]
- [ ] **Describe the bug**
在运行一个python工程的时候，gd导航到定义时，遇到问题：method textDocument/completion is not supported by any of the servers registered for the current buffer
- [ ] **nvim --version**
v0.9.2
- [ ] **Operating System**
ubuntu 22.04
- [ ] **checkhealth screenshot**
checkhealth结果没法保存所以没法完整提供，null-ls缺少presitter和stylua，还不知道怎么安装。其它的就没有ERROR了。

**Comment by Martins3** [comment]
> 在运行一个python工程的时候，gd导航到定义时，遇到问题：method textDocument/completion is not supported by any of the servers registered for the current buffer

```sh
#!/usr/bin/env bash
set -E -e -u -o pipefail

cd /tmp
mkdir -p test_nvim_project
cd test_nvim_project
git init
cat << '_EOF_' > a.py
def test():
    print("martins3")

if __name__ == "__main__":
    test()
_EOF_
nvim a.py
```
执行这个脚本，看看在 test 中 gd 会报错吗?


> checkhealth结果没法保存所以没法完整提供，null-ls缺少presitter和stylua，还不知道怎么安装。其它的就没有ERROR了

这个可以截个图

**Comment by yhl41001** [comment]
> > 在运行一个python工程的时候，gd导航到定义时，遇到问题：method textDocument/completion is not supported by any of the servers registered for the current buffer
> 
> ```shell
> #!/usr/bin/env bash
> set -E -e -u -o pipefail
> 
> cd /tmp
> mkdir -p test_nvim_project
> cd test_nvim_project
> git init
> cat << '_EOF_' > a.py
> def test():
>     print("martins3")
> 
> if __name__ == "__main__":
>     test()
> _EOF_
> nvim a.py
> ```
> 
> 执行这个脚本，看看在 test 中 gd 会报错吗?
> 
1、把上面的脚本全部复制到a.py文件中，执行python a.py命令，报错：
❯ python a.py
  File "/home/yuhailong/Doc/a.py", line 2
    set -E -e -u -o pipefail
                    ^^^^^^^^
SyntaxError: invalid syntax
2、nvim a.py打开文件，gd函数test，报错和以前是一样的
> > checkhealth结果没法保存所以没法完整提供，null-ls缺少presitter和stylua，还不知道怎么安装。其它的就没有ERROR了
> 
> 这个可以截个图
![image](https://github.com/Martins3/My-Linux-Config/assets/3931087/ee260338-ba8e-4fb9-a62c-b71afec7caf6)

**Comment by Martins3** [comment]
:laughing: 你理解错误我的意思了，执行这个脚本会自动创建一个 a.py ，不是将 bash 的代码拷贝到 python 中。你重新执行下，截图给我看看

**Comment by yhl41001** [comment]
问题已经解决了，没有安装pyright，执行如下命令可以解决：
sudo npm install -g pyright

还有一个问题需要请教一下，用gd跳到定义处后，光标回退用的哪个命令，为还没有找到，能麻烦提供一下么？

**Comment by Martins3** [comment]
> 问题已经解决了，没有安装pyright，执行如下命令可以解决： sudo npm install -g pyright

下个版本中，会用 mason 来自动安装大部分 lsp server，到时候应该不会遇到这个问题

> 还有一个问题需要请教一下，用gd跳到定义处后，光标回退用的什么命令？我还没有找到，能麻烦提供一下么？

试试 ctrl  o

**Comment by yhl41001** [comment]
> > 问题已经解决了，没有安装pyright，执行如下命令可以解决： sudo npm install -g pyright
> 
> 下个版本中，会用 mason 来自动安装大部分 lsp server，到时候应该不会遇到这个问题
这个版本，为已经折腾两三个周了，最近问了你不少问题，目前已经基本都把问题解决了，也不敢再升级了，可以先这样用着，目前能满足我的要求了，非常感谢分享和快速回答问题！
> 
> > 还有一个问题需要请教一下，用gd跳到定义处后，光标回退用的什么命令？我还没有找到，能麻烦提供一下么？
> 
> 试试 ctrl o

试过了，没问题，可以回退，多谢！

**Comment by Martins3** [comment]
:rofl: vim 前期入手确实比较难
