### ISSUE TITLE
built-in lsp

### ISSUE THREAD

**Issue by Martins3** [Martins3/My-Linux-Config#15]
I noticed that built-in lsp and using lua as config script became more and more mature and popular, maybe we should follow the trending, but before taking any actions we should find out enough evidence proving there are overwhelming advantages comparing to current configurations.

Built-in lsp and lua related material will be collected and put below.

**Comment by Martins3** [comment]
- [ ] https://github.com/neovim/nvim-lspconfig

**Comment by Martins3** [comment]
- [ ] https://github.com/nvim-telescope/telescope.nvim -> fzf

**Comment by Martins3** [comment]
- https://crispgm.com/page/neovim-is-overpowering.html

**Comment by Martins3** [comment]
Some plugins begin to only provide Neovim version:
-  https://github.com/vhyrro/neorg

**Comment by Martins3** [comment]
4. [NVCode](https://github.com/ChristianChiarulli/nvim) 基于 coc.nvim 的一个配置

**Comment by Martins3** [comment]
https://github.com/NvChad/NvChad

**Comment by xiaoLeeFeiDao** [comment]
安装不了插件，53个一个都装不了，全部报错
Failed to install ***
源也更新成国内的了 这个是啥原因呢？

**Comment by Martins3** [comment]
> 安装不了插件，53个一个都装不了，全部报错 Failed to install *** 源也更新成国内的了 这个是啥原因呢？

你可以在这里创建一个新的 issue 来说明一下你的环境
https://github.com/Martins3/My-Linux-Config/issues/new?assignees=Martins3&labels=&template=it-doesn-t-work-for-me.md&title=

**Comment by xiaoLeeFeiDao** [comment]
您好 我已经安装上了 报错的原因是我的clash没关闭导致13.03.2022, 19:17, "Martin Three" ***@***.***>:

安装不了插件，53个一个都装不了，全部报错 Failed to install *** 源也更新成国内的了 这个是啥原因呢？

你可以在这里创建一个新的 issue 来说明一下你的环境
https://github.com/Martins3/My-Linux-Config/issues/new?assignees=Martins3&labels=&template=it-doesn-t-work-for-me.md&title=
