### ISSUE TITLE
设置tab为四个空格

### ISSUE THREAD

**Issue by yhl41001** [Martins3/My-Linux-Config#152]
您好，有个问题麻烦请教一下。
目前在编辑代码时，tab键好像是8个空格，修改哪里的配置可以改为4个空格。
我没找到在哪里修改，多谢！

**Comment by Martins3** [comment]
我建议用 editorconfig，例如这个项目中:
https://github.com/Martins3/My-Linux-Config/blob/master/.editorconfig

因为不同的项目中要求不同，例如 Linux kernel 就强制要求为 tab ，在项目的根目录中放一个 .editorconfig 更好点。

具体使用参考 : https://editorconfig.org/


如果你还是想要在 vim 中配置，可以把 set tabstop=4 加入到 https://github.com/Martins3/My-Linux-Config/blob/master/nvim/init.vim 中

**Comment by yhl41001** [comment]
收到，多谢！
