### ISSUE TITLE
mac os 报错

### ISSUE THREAD

**Issue by Hehe72-lang** [Martins3/My-Linux-Config#160]
大神 我在用m1 mac air配置的时候一直报一个错:
33 lua require 'usr'
这一行报
[im-select]: binary tools missed, please follow installation manual in README

我本机是安装了lua的，很奇怪 网上也没找到解决方案

- [ ] **nvim --0.9.5**
- 
- [ ] **14.4.1 (23E224)**
- [ ] **checkhealth screenshot**
E5009: Invalid $VIMRUNTIME: nvim-macos-arm64/share/nvim/runtime
Error executing lua: function health#gitmessenger#check[1]..<SNR>123_check_job, line 4: Vim(call):E117: Unknown functio
n: health#report_ok
stack traceback:
        [C]: in function 'call'
        ...s/nvim-macos-arm64/share/nvim/runtime/lua/vim/health.lua:366: in function '_check'
        [string "<nvim>"]:1: in main chunk

**Comment by Hehe72-lang** [comment]
100 null-ls: require("null-ls.health").check()
  101
  102 - ERROR prettier: the command "prettier" is not executable.
  103 - ERROR black: the command "black" is not executable.
  104 - ERROR stylua: the command "stylua" is not executable.


 231 - ERROR rg: not found. live-grep finder will not function without [BurntSushi/ripgrep](https://github.com/
      BurntSushi/ripgrep) installed.

**Comment by Martins3** [comment]
https://github.com/Martins3/My-Linux-Config/blob/master/docs/nvim.md#%E5%AE%89%E8%A3%85%E5%90%84%E7%A7%8D-lsp

执行下 :Mason 看看

**Comment by UncleWangNearBy** [comment]
我这也碰到了这个问题，
执行:Mason  看起来没有异常，并且我的mac和centos 7均有上述问题

**Comment by Martins3** [comment]
将 https://github.com/Martins3/My-Linux-Config/blob/64e3e63f03457328bb889512842055b2ebcde145/nvim/lua/usr/init.lua#L25 删除掉，不加载它。这个插件是做 输入法自动切换的。

**Comment by Martins3** [comment]
之后会补充对应的说明

**Comment by UncleWangNearBy** [comment]
> 之后会补充对应的说明

感谢

**Comment by Martins3** [comment]
更新了，这个插件被 disable 了
