### ISSUE TITLE
一处笔误

### ISSUE THREAD

**Issue by lansoa** [Martins3/My-Linux-Config#161]
commit d49f5ae0ee4456a9468a962d84691ec0eea4a6b4 (HEAD -> lyz, master)
Author: lanyanzhi <lanyanzhi22b@ict.ac.cn>
Date:   Tue Jul 16 11:37:59 2024 +0800

    docs: fix a tiny wrong word
    
    Signed-off-by: lanyanzhi <lanyanzhi22b@ict.ac.cn>

diff --git a/docs/why.md b/docs/why.md
index a487813..b32d470 100644
--- a/docs/why.md
+++ b/docs/why.md
@@ -14,7 +14,7 @@
 4. 社区，我大年 30 都不回家，这里各个都是人才，说话又好听，超喜欢在里面的。
 
 ## 折腾
-1. 看似慢，实则块。
+1. 看似慢，实则快。
 
 有的人写代码不写单元测试，项目不配置 ci ，代码风格随意，重复的代码不做抽象等。
 这些操作看似可以加快项目的推进速度，实际上最后会导致各种低级 bug 层出不穷，得不偿失。

**Comment by Martins3** [comment]
直接提交 pr 吧
