### ISSUE TITLE
python 文件 import 当前目录下的文件, lsp 不认识

### ISSUE THREAD

**Issue by whitelilis** [Martins3/My-Linux-Config#165]
- [ ] **Describe the bug**
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/6319ce9a-7d91-46a6-87df-d7a076123d25">

- [ ] **nvim --version**
0.11.0
- [ ] **Operating System**
macos
- [ ] **checkhealth screenshot**

**Comment by Martins3** [comment]
只有 python 有问题，还是其他的也有问题，可以提供一个最小复现环境吗？

**Comment by whitelilis** [comment]
目前只发现 python 有问题.
把附件里的压缩包打开, 有两个 python 文件.
nvim bb.py
如下图

<img width="927" alt="image" src="https://github.com/user-attachments/assets/4b312027-8ab0-4b40-afda-d039eeba7ee7">

**Comment by whitelilis** [comment]
[nn.tgz](https://github.com/user-attachments/files/16708622/nn.tgz)

**Comment by Martins3** [comment]
在这个目录执行下 git init

**Comment by whitelilis** [comment]
> 在这个目录执行下 git init

果然这样就管用了.
但是如果这个目录本身已经是在一个 git 仓库里, 但不是顶级目录呢? 比如目录结构是这样的:
.
├── .git
│   ├── HEAD
│   ├── config
│   ├── description
│   ├── hooks
│   ├── info
│   ├── objects
│   └── refs
├── .gitlab
│   └── pipeline
├── .gitlab-ci.yml
└── nn
    ├── aa.py
    └── bb.py

对于 python 根目录的判断不应该依赖于 git 吧?

**Comment by Martins3** [comment]
这个就不是 neovim 的问题，而是 python 语法的问题了 😆

**Comment by whitelilis** [comment]
我其实想知道 python 的lsp (pyright ?) 是怎么判断 项目的根目录的, 然后看有没有地方设置它. 这样直接跟 git 的根目录绑定, 感觉不科学. 
比如 vscode 和 intellij 这种 ide 都能正确识别出来. 
vscode 内部用的 lsp也只是个升级版的 pyright

**Comment by Martins3** [comment]
这个配置用的是 pyright 的特殊配置，这个你需要看看 pyright 的文档，vscode 、 intellij 也许有特殊的配置

**Comment by whitelilis** [comment]
https://github.com/neovim/nvim-lspconfig/issues/2238
这里说, 要检查包含以下几个文件的地方做为 root
```
 local root_files = { 
   'pyproject.toml', 
   'setup.py', 
   'setup.cfg', 
   'requirements.txt', 
   'Pipfile', 
   'pyrightconfig.json', 
 }
```

发现添加一个 requirements.txt 之后就可以解决我上面例子里的那个问题了. 

但是在我的另一个目录里, 有这个文件,还是不管用,哈哈. 暂关了吧

**Comment by whitelilis** [comment]
done now.

**Comment by whitelilis** [comment]
最终破案了: 不管用的目录里, 有个 requirments.txt, 是某位同学写错了.......... 改名成 requirements.txt 就可以了.
