### ISSUE TITLE
ccls is incorrecty set

### ISSUE THREAD

**Issue by 54108** [Martins3/My-Linux-Config#166]
- [ ] **Describe the bug**
- [ ] 完全按照安装步骤进行，但是在cpp文件下ccls不会被触发
- [ ] 
![Screenshot_2024-08-30-01-20-58-459_com termux](https://github.com/user-attachments/assets/32e2abfa-47f5-47a3-8ba7-e96316d56bb6)
- [ ] **nvim --version**
- [ ] NVIM v0.9.5
- [ ] **Operating System**
- [ ] Debian sid（termux）
- [ ] **checkhealth screenshot**
- [ ] 
![Screenshot_2024-08-30-01-32-12-022_com termux](https://github.com/user-attachments/assets/387b03cb-8c67-4288-8374-c7fdcb2c0823)

**Comment by 54108** [comment]
sorry,my problem.
It works when I've used cmake to generate compile_commands.json.

**Comment by 54108** [comment]
![Screenshot_2024-08-31-13-54-53-450_com termux](https://github.com/user-attachments/assets/96980382-cf23-42aa-a2bd-b88c86a097eb)
仍然有一些问题，不知为何ccls没有被正确触发。

**Comment by Martins3** [comment]
执行 :LspLog  看看

看看 compile_comands.json 的内容

有生成 .ccls-cache 吗？

**Comment by 54108** [comment]
1：
![Screenshot_2024-09-01-10-56-19-541_com termux](https://github.com/user-attachments/assets/e6f65b2d-46a7-42fe-8907-002b00c79ec5)
![Screenshot_2024-09-01-10-56-12-684_com termux](https://github.com/user-attachments/assets/af1de30a-fd69-4915-a4fc-25c06c2eb0dc)
![Screenshot_2024-09-01-10-56-01-397_com termux](https://github.com/user-attachments/assets/ddb4f887-3ef3-48ea-9de1-d3d36f8c1381)
![Screenshot_2024-09-01-10-55-47-602_com termux](https://github.com/user-attachments/assets/88ee339d-9064-4c91-ae22-c8bf20763f88)
![Screenshot_2024-09-01-10-55-38-943_com termux](https://github.com/user-attachments/assets/43d2b1c5-0f01-4315-9971-fbfb3ac4bde2)
2：
![Screenshot_2024-09-01-10-56-41-091_com termux](https://github.com/user-attachments/assets/428da59a-5712-4561-9894-1e5fb45609ef)
3：有
![Screenshot_2024-09-01-10-54-39-283_com termux](https://github.com/user-attachments/assets/b12e6cca-47d0-409b-8157-95bbdbb5566f)

**Comment by 54108** [comment]
[lsp.log](https://github.com/user-attachments/files/16834876/lsp.log)

**Comment by 54108** [comment]
已照做
[lsp.log](https://github.com/user-attachments/files/16843423/lsp.log)

**Comment by Martins3** [comment]
看上去没什么问题。如果你测试一个 hello world 的项目也会有问题吗？

我看的源码中引用一些库，但是 compile_comands.json 中没有引用这些库。

**Comment by 54108** [comment]
单纯的测试并没有问题。可能是cmake生成的compile_commands.json如你所说有问题。
![Screenshot_2024-09-03-13-10-00-509_com termux](https://github.com/user-attachments/assets/6d3027ce-2f21-4359-8a2f-0799b3006050)

**Comment by 54108** [comment]
> 看上去没什么问题。如果你测试一个 hello world 的项目也会有问题吗？
> 
> 我看的源码中引用一些库，但是 compile_comands.json 中没有引用这些库。

破案了，是CMake生成的compile_commands.json问题。但是我没有更好的解决方案了。
