### ISSUE TITLE
which-key 的warning 提示好烦,可以关掉吗?

### ISSUE THREAD

**Issue by whitelilis** [Martins3/My-Linux-Config#167]
- [ ] **Describe the bug**
每次都出现这个 which-key 的提示,好烦,可以关掉吗?
<img width="688" alt="image" src="https://github.com/user-attachments/assets/7d857ddb-d444-4d1b-a119-fa20e5c271e1">

- [ ] **nvim --version**
- [ ] **Operating System**
- [ ] **checkhealth screenshot**

**Comment by Martins3** [comment]
嗯嗯，你 checkout 到 https://github.com/Martins3/My-Linux-Config/tree/feature 这个分支看看还有问题吗?

**Comment by Martins3** [comment]
新版本更新了，应该解决这个问题了
