### ISSUE TITLE
如何配置 ccls 的并行度呢？

### ISSUE THREAD

**Issue by Datebasesystem** [Martins3/My-Linux-Config#173]
现在开启项目后，ccls 默认是使用所有的核来构建索引的，这个怎么能限制一下使用的核数呢？

**Comment by Martins3** [comment]
https://github.com/Martins3/My-Linux-Config/blob/14516e5e74d4fd1a36d88ba931342f093dffd19b/nvim/lua/usr/lsp/settings/ccls.lua#L4  配置这个

**Comment by Datebasesystem** [comment]
🐂🍺，感谢大佬
