### ISSUE TITLE
spectre 搜索结束后，如何在打开文件的同时关闭搜索框

### ISSUE THREAD

**Issue by Datebasesystem** [Martins3/My-Linux-Config#175]
- What's your suggestion?
大佬🙏
通过 space s p 打开  spectre 的搜索框后，是这样的。
<img width="587" alt="image" src="https://github.com/user-attachments/assets/d44441c2-1230-4a3c-967d-2aa2458316c6" />

在点击文件 nvim/init.vim: 后，是没办法自动把 spectre 搜索框关闭掉的，这个和之前 SpaceVim 的行为有点不一致，可以改成打开一个文件后自动关闭 spectre 搜索框吗？
- Why is this better?
- How to implement your ideas?

**Comment by Martins3** [comment]
我一般用   spectre 做 project 基本的替换，如果是搜索的话，`,` `g` 就可以了。

**Comment by Datebasesystem** [comment]
> 我一般用 spectre 做 project 基本的替换，如果是搜索的话，`,` `g` 就可以了。

`,` `g` 的问题在于，没办法直接用当前单词来查找，比如 `,``G` 直接搜索当前单词，这种能实现吗？
