### ISSUE TITLE
跳转到下一个出错的位置

### ISSUE THREAD

**Issue by Datebasesystem** [Martins3/My-Linux-Config#176]
- [ ] **Describe the bug**

以前 SpaceVIm 版本，有一个快捷键是 gn，跳转到代码中下一个出错的位置。现在这个版本没有了么。。
- [ ] **nvim --version**
- [ ] **Operating System**
- [ ] **checkhealth screenshot**

**Comment by Martins3** [comment]
我一般用  g w ，然后在 telescope 中选择

**Comment by Datebasesystem** [comment]
可以加一个配置
```
+  { "gn", "<cmd>lua vim.diagnostic.goto_next()<cr>",               desc = "go to next error" },
+  { "gN", "<cmd>lua vim.diagnostic.goto_prev()<cr>",               desc = "go to prev error" },
+
```
就和原来coc的一致了

**Comment by Martins3** [comment]
提一个 pr ，我给加上

**Comment by Datebasesystem** [comment]
https://github.com/Martins3/My-Linux-Config/pull/178
