### ISSUE TITLE
cmake supporting??

### ISSUE THREAD

**Issue by JianqiangDing** [Martins3/My-Linux-config#2]
Hi,  I am a new vimer,  it seems that it does not support to maintain the project with CMake? am I wrong somewhere? I've run  "bear make" after initializing the project using CMake, but it looks like there is no linking between *.h file and related *.cpp file,  any suggestion? here is a piece of a screenshot illustrating the issue:

I was using [polyscope](https://github.com/nmwsharp/polyscope) as the test case, any suggestion would be helpful.

![image](https://user-images.githubusercontent.com/7833870/79062597-79fdba00-7cce-11ea-9c66-6bcf1ca77d26.png)

**Comment by Martins3** [comment]
Thanks for your feedback!
1. Can you tell me your ccls version ?
2. Check compile_commands.json that `bear make` generates.

**Comment by Martins3** [comment]
I try the project, it works for me.
I guess you didn't put `compile_commands.json` at the root directory of `polyscope`
![image](https://user-images.githubusercontent.com/16731244/79086032-402fc080-7d6d-11ea-84cc-4ed7612bb86c.png)

**Comment by JianqiangDing** [comment]
you are right, there are some dependencies of ccls broken,  which lead to the ccls performing wired, so I just clean related dirs then reinstall all of them and everything is fine now.
thanks for your response， great tutorial!!!
(you may close the issue now)
