### ISSUE TITLE
在窗口中新建文件问题

### ISSUE THREAD

**Issue by huerni** [Martins3/My-Linux-config#24]
你好，我想在spacevim内新建文件，我用的是 space+b+N新建一个buffer，然后用vim命令file+文件名，但编辑的时候没有高亮那些，就是不认为是cpp文件，要退出重新进插件才有作用，我想问下要怎么在spcaevim窗口内新建文件？

**Comment by Martins3** [comment]
在文件树上  `shift + n` 创建新的文件，参考 https://github.com/SpaceVim/SpaceVim/blob/3f3a4912dfdfe70989f4a10536173dcab7614443/config/plugins/defx.vim#L145

**Comment by huerni** [comment]
哦哦哦  谢谢
