### ISSUE TITLE
如何去掉光标所在行的git提示？

### ISSUE THREAD

**Issue by marryton007** [Martins3/My-Linux-config#26]
首先感谢大佬的分享，让我节省了不少时间。

问题见下图：
![image](https://user-images.githubusercontent.com/2311328/129311862-b102d26c-4138-4258-af8f-f24b58d16c73.png)

请问一下，如何去掉光标所在行的git提示呢？

**Comment by Martins3** [comment]
哦哦，这个自动显示 git blame 的操作，将 https://github.com/Martins3/My-Linux-config/blob/65f4d778b8f44b4614d3d9ea5b8e41c6d18fbd9f/plugin/coc.vim#L47 就好了，也就是下面两行
```vim
call coc#config("git.addGBlameToVirtualText", v:true)
call coc#config("git.virtualTextPrefix", "👋 ")
```

**Comment by Martins3** [comment]
我猜这个问题你已经解决了，那我就关闭这个 issue 了，有任何问题，重开这个 issue 就可以了。

**Comment by marryton007** [comment]
多谢，已经解决。
