### ISSUE TITLE
how to jump back after call coc-definition?

### ISSUE THREAD

**Issue by marryton007** [Martins3/My-Linux-config#28]
大佬，你好。

操作环境： ubuntu18.04
~/.SpaceVim.d$ nvim -v
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-878

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

直接使用你的配置已经可以浏览代码了，只是有一个问题：

在使用,gd跳到一个函数定义之后，使用ctro+o可以跳转回原来的位置。但如果使用jkhl移动了光标，就不能使用ctrl+o到跳回原地址了。这导致在浏览内核代码时，非常不方便。

请问应该如何操作才可以快速跳回原来的位置，就像以前用ctags的ctrl+[和ctrl+]一样

![image](https://user-images.githubusercontent.com/2311328/131294922-60d2eeab-827a-4c58-9fc6-a609340a077e.png)

**Comment by Martins3** [comment]
因为我的配置是来来自于 coc.nvim 的，所以 可以参考下面两个 issue
- https://github.com/neoclide/coc.nvim/issues/3044
- https://github.com/neoclide/coc.nvim/issues/1026

具体做法就是
1. 增加配置 `set tagfunc=CocTagFunc`
2. 删除我之前对于 cltr [  的映射 


https://github.com/Martins3/My-Linux-config/blob/65f4d778b8f44b4614d3d9ea5b8e41c6d18fbd9f/autoload/myspacevim.vim#L42
3. 使用 ctrl [ 来跳转而不是 gd

**Comment by marryton007** [comment]
非常感谢，按你所说修改之后。

使用ctrl+] 跳到定义处，ctrl+t 跳回， 但不能与,gd混用

**Comment by marryton007** [comment]
非常感谢，按你所说修改之后。

使用ctrl+] 跳到定义处，ctrl+t 跳回， 但不能与,gd混用

**Comment by marryton007** [comment]
感谢大佬的回复，闹了个乌龙。

服务器被人挖矿攻击了，导致ccls运行缓慢，不能及时响应。

**Comment by Martins3** [comment]
> 感谢大佬的回复，闹了个乌龙。
> 
> 服务器被人挖矿攻击了，导致ccls运行缓慢，不能及时响应。

好吧，这也可以，可笑死我了。
