### ISSUE TITLE
怎样控制coc-definition跳转的位置

### ISSUE THREAD

**Issue by chengpengzhao** [Martins3/My-Linux-Config#30]
假设我的项目文件夹是这样的，源代码都在`src`里，以前用ctags只需要在根目录运行vim，就会自动生成跳转相应的文件。
```
├── .git
├── doc
├── LICENSE
├── README.md
├── SConstruct
├── src
├── test

```

现在用coc-definition后，需要根据编译后生成的compile_commands.json文件实现跳转，目录变成了这样：  
```
├── .git
├── build
├── compile_commands.json
├── doc
├── install
├── LICENSE
├── README.md
├── SConstruct
├── src
├── test
```
用coc.nvim里的跳转只能跳转到`install/include`文件夹中的文件，而大多数情况下我是想修改`src`里的相应文件，而不是打开`install`里的文件。     

不知道用其他编译工具生成的`compile_commands.json`也有这种问题么

**Comment by Martins3** [comment]
> 用coc.nvim里的跳转只能跳转到`install/include`文件夹中的文件，而大多数情况下我是想修改`src`里的相应文件，而不是打开`install`里的文件。    

是 `include` 里面的文件吧?

**Comment by Martins3** [comment]
因为信息有限，我说一下我的猜测:
1.  也许使用 coc-implementation  来跳转。
```viml
" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references-used)
```
2. compile_comands.json 生成的不对，其中包含那些 src 的内容。

如果可以的话，你可以将这个项目的 github 链接给出来看看。如果这是 private 的，你可以制作一个 minimal 的案例吗?

**Comment by Martins3** [comment]
Maybe your problem has been fixed, if any question, just reopen the issue.
