### ISSUE TITLE
As a fresh-user

### ISSUE THREAD

**Issue by specialpointcentral** [Martins3/My-Linux-Config#31]
- `fzf` can be auto-installed by first use
- `ctags` need not be installed
- `nodejs` > 14
- `cppman`
- nerd font

**Comment by specialpointcentral** [comment]
- markdown-preview 需要装`yarn`，并且进入手动安装（也有可能是`yarn`没有提前安装导致）
- 在完成前面后，还需要手动再装`coc`

**Comment by specialpointcentral** [comment]
markdown-preview.nvim总是无法building成功

**Comment by specialpointcentral** [comment]
F5的使用好像没写

**Comment by Limaomao821** [comment]
# 修改字体
## 下载
https://www.nerdfonts.com/font-downloads
## 安装
https://gist.github.com/matthewjberger/7dd7e079f282f8138a9dc3b045ebefa0

**Comment by Martins3** [comment]
- cargo install tree-sitter-cli

**Comment by Martins3** [comment]
- ln -s $(which fdfind) ~/.local/bin/fd

**Comment by Martins3** [comment]
- pip install ueberzug
