### ISSUE TITLE
工程中搜索报错，pointer being freed was not allocated

### ISSUE THREAD

**Issue by Jack126** [Martins3/My-Linux-Config#32]
Martins3 ，你好：

问题一：在阅读readme过程中，尝试使用  "， s"  搜索获得结果后，到某个方法上执行 "gr"  ，spacevim会闪退。提示错误 pointer being freed was not allocated. 

问题二："，s " 可以搜索工程中文件，而在navigate 中  "，s + 文件" 可以搜索文件，这一步骤，没看明白，我输入", s "后，还是搜索工程中的文件，而不是截图提供的样子。能否详细说一下，感谢🙏

**Comment by Martins3** [comment]
- `,` `s` 被配置为搜索真正工程中的符号，在 section navigate 中我写错了，感谢指出来。
- `,` `f` 是搜索文件

关于问题一，能否提供更多的信息
- neovim 版本 (似乎 0.5.0 上的版本并不稳定)
- crash 的截图

**Comment by Jack126** [comment]
> * `,` `s` 被配置为搜索真正工程中的符号，在 section navigate 中我写错了，感谢指出来。
> * `,` `f` 是搜索文件
> 
> 关于问题一，能否提供更多的信息
> 
> * neovim 版本 (似乎 0.5.0 上的版本并不稳定)
> * crash 的截图

嗨，Martins3，感谢回复
我用的neovim版本是0.5.0，我切换0.4.0 试试
crash 截图？这是什么

**Comment by Martins3** [comment]
> 到某个方法上执行 "gr" ，spacevim会闪退。提示错误 pointer being freed was not allocated.

最近我升级到  neovim 高版本的时候，整个 neovim 会直接 coredump，你可以把 "提示错误 pointer being freed was not allocated." 的整个终端的截图给我看看

**Comment by Jack126** [comment]
> > 到某个方法上执行 "gr" ，spacevim会闪退。提示错误 pointer being freed was not allocated.
> 
> 最近我升级到 neovim 高版本的时候，整个 neovim 会直接 coredump，你可以把 "提示错误 pointer being freed was not allocated." 的整个终端的截图给我看看

mac 切换 0.4.4版本好麻烦，哈哈，绿色源码整上了0.4.4，问题修复。看来是0.5的版本问题，多谢 ！ Thank U ， Martins3

**Comment by Martins3** [comment]
> mac 切换 0.4.4版本好麻烦，哈哈，绿色源码整上了0.4.4，问题修复。看来是0.5的版本问题，多谢 ！ Thank U ， Martins3

Ubunutu 上比较保守，还是 0.4.4，什么是 "绿色源码"? 0.5 的问题我最近花点时间找找，你出现 core dump 的问题可以稳定复现吗?

**Comment by Jack126** [comment]
> > mac 切换 0.4.4版本好麻烦，哈哈，绿色源码整上了0.4.4，问题修复。看来是0.5的版本问题，多谢 ！ Thank U ， Martins3
> 
> Ubunutu 上比较保守，还是 0.4.4，什么是 "绿色源码"? 0.5 的问题我最近花点时间找找，你出现 core dump 的问题可以稳定复现吗?

用的 tar包源码 https://github.com/neovim/neovim/releases/download/v0.4.4/nvim-macos.tar.gz ，直接运行绑定就可以用，绿色环保，哈哈。回滚到0.4版本后，未复现之前问题

**Comment by Martins3** [comment]
回滚其实权宜之计，最好是直接找到 bug，不过感觉 core dump 很难复现，暂时就没有去搞了。

**Comment by Jack126** [comment]
> 回滚其实权宜之计，最好是直接找到 bug，不过感觉 core dump 很难复现，暂时就没有去搞了。

我家里电脑还是0.5，我晚上回去看看怎么复现试试。
对了，有没有方法将 plugin的安装 首选走 git 而不是https，我发现用你的配置下载plugin特别慢。。。当然网的问题也是一方面

**Comment by Martins3** [comment]
> 对了，有没有方法将 plugin的安装 首选走 git 而不是https，我发现用你的配置下载plugin特别慢。。。当然网的问题也是一方面

我写了一个科学上网的教程，一旦成功之后，可以配置 git 代理，git 走 https 代理了之后，速度应该会非常快
https://martins3.github.io/gfw.html
```
git config --global http.proxy http://127.0.0.1:8889
git config --global https.proxy https://127.0.0.1:8889
```

**Comment by Jack126** [comment]
> > 对了，有没有方法将 plugin的安装 首选走 git 而不是https，我发现用你的配置下载plugin特别慢。。。当然网的问题也是一方面
> 
> 我写了一个科学上网的教程，一旦成功之后，可以配置 git 代理，git 走 https 代理了之后，速度应该会非常快
> https://martins3.github.io/gfw.html
> 
> ```
> git config --global http.proxy http://127.0.0.1:8889
> git config --global https.proxy https://127.0.0.1:8889
> ```

我也是挂的代理，小灰机。。我晚上回去试试你的代理方法

**Comment by Jack126** [comment]
> > 对了，有没有方法将 plugin的安装 首选走 git 而不是https，我发现用你的配置下载plugin特别慢。。。当然网的问题也是一方面
> 
> 我写了一个科学上网的教程，一旦成功之后，可以配置 git 代理，git 走 https 代理了之后，速度应该会非常快
> https://martins3.github.io/gfw.html
> 
> ```
> git config --global http.proxy http://127.0.0.1:8889
> git config --global https.proxy https://127.0.0.1:8889
> ```

嗨，录屏已发送你gmail邮箱，请注意查收，感谢

**Comment by Martins3** [comment]
似乎找到了一些原因，我在 2021 那个 branch 中使用 telescope-coc.nvim 来实现 `,` `s` 的功能之后，这个问题就可以避免了。当然 neovim 显然是有 bug 的，无论如何都不应该 core dump 的。

**Comment by Jack126** [comment]
> 似乎找到了一些原因，我在 2021 那个 branch 中使用 telescope-coc.nvim 来实现 `,` `s` 的功能之后，这个问题就可以避免了。当然 neovim 显然是有 bug 的，无论如何都不应该 core dump 的。

我用的spacevim1.7   neovim 0.4.4
