### ISSUE TITLE
文件搜索时，文件名字相同的情况下如何选择

### ISSUE THREAD

**Issue by Jack126** [Martins3/My-Linux-Config#34]
嗨，Martins3，我又来了

目前遇到这么一个问题，工程项目中搜索一个文件名字(, f)，当有多个文件相同的文件名字时，如何选
![WX20210930-152456](https://user-images.githubusercontent.com/3423503/135406722-d5f52ba4-7999-4b37-abe8-7c20e6416b04.png)

**Comment by Martins3** [comment]
1. 使用 tab 进入 normal 模式
2. 然后 jk 移动

**Comment by Martins3** [comment]
具体可以参考 leaderf 的文档

**Comment by Martins3** [comment]
如果解决那我就关闭这个 issue 了哦。没解决可以来讨论。
