### ISSUE TITLE
Cmake 时遇到错误

### ISSUE THREAD

**Issue by wz1114841863** [Martins3/My-Linux-Config#35]
![2021-10-02 18-02-17屏幕截图](https://user-images.githubusercontent.com/60866264/135711723-578389a6-d3a6-4894-b6a4-55fe7e80ba21.png)
刚开始看到的是您在简书发表的一篇blog，然后那个博客上的nvim是直接下载的，不用编译，一直到最后一步，下载了您提供的配置文件后打开显示出现了一些配置错误，显示需要最新版本的nvim（0.5以上），然后就把那个nvim就卸载了，找到了这个仓库，将结果编译失败，不知道您是否指导这是什么问题，或者有没有之前旧的配置文件。

**Comment by Martins3** [comment]
- 因为有一些插件需要 neovim 0.5 的特性，所以需要手动编译一个新的 neovim，如果你不想使用新的 neovim 的，可以继续使用之前的版本: 9d23913c4fb1e1aa06476da6272048ebf4251406
- 但是，我建议还是使用新的版本的 neovim，因为我之前发现在 0.4.4 的 neovim 上，SpaceVim 的 grep 无法使用 tab 进行搜索内容的选择。
- 编译之所以出现错误，应该是因为下载第三方应用的时候没有加上代理。至于科学上网的方法可以参考我之前的一个 blog https://martins3.github.io/gfw.html

**Comment by wz1114841863** [comment]
十分感谢！没想到会收到邮件，我会接着尝试的。


来自 魅蓝 Note6

**Comment by Martins3** [comment]
> 十分感谢！没想到会收到邮件，我会接着尝试的。 来自 魅蓝 Note6

:laughing:  这个是 github 的默认通知方式，可以自己设置。
