### ISSUE TITLE
[help needed] Have two small question after installation.

### ISSUE THREAD

**Issue by hypghzy** [Martins3/My-Linux-Config#39]
I have manually fixed the first one but it is not a solid solution. 
The telescope cannot find the fzf extension. The error message indicated that the telescope was looking for  libfzf.so in ~/.cache/vimfiles/.cache/init.vim/.dein/build directory. I found that file in the cached git repo ~/.cache/vimfiles/repos/github.com/nvim-telescope/telescope-fzf-native.nvim/build. I am still new to this, so I cannot find out a good solution for that.

Another question is the error message "[dein] Vim(let):E745: Using a List as a Number" always pop up when I change into Insert mode for the first time that I open the neovim. I have googled that message and only got an irrelevant post. Is there anyone have seen this message before?

**Comment by Martins3** [comment]
firstly, thanks for your report.
## problem one
I can't reproduce it. In ~/.cache/vimfiles/.cache/init.vim/.dein/build, there is only one file:
```
➜  build pwd
/home/maritns3/.cache/vimfiles/.cache/init.vim/.dein/build
➜  build l
drwxrwxr-x maritns3 maritns3   4 KB Tue Sep  7 19:57:59 2021  .
drwxrwxr-x maritns3 maritns3   4 KB Sat Nov 20 22:11:26 2021  ..
.rw-rw-r-- maritns3 maritns3 1.1 MB Tue Sep  7 19:58:00 2021  index.js
```
Maybe, updating spacevim(by command `SPUpdate`) can solve your problem.
## problem two
it's confirmed and I'll try to fix it.

**Comment by Martins3** [comment]
I found the bug, just remove
```vim
let g:neosnippet#snippets_directory='~/.cache/vimfiles/repos/github.com/honza/vim-snippets/snippets'
```

**Comment by hypghzy** [comment]
> firstly, thanks for your report.
> ## problem one
> 
> I can't reproduce it. In ~/.cache/vimfiles/.cache/init.vim/.dein/build, there is only one file:
> 
> ```
> ➜  build pwd
> /home/maritns3/.cache/vimfiles/.cache/init.vim/.dein/build
> ➜  build l
> drwxrwxr-x maritns3 maritns3   4 KB Tue Sep  7 19:57:59 2021  .
> drwxrwxr-x maritns3 maritns3   4 KB Sat Nov 20 22:11:26 2021  ..
> .rw-rw-r-- maritns3 maritns3 1.1 MB Tue Sep  7 19:58:00 2021  index.js
> ```
> 
> Maybe, updating spacevim(by command `SPUpdate`) can solve your problem.
> ## problem two
> 
> it's confirmed and I'll try to fix it.

Thanks for fixing it.
Regarding the question one, I did some changes on the installation which may cause some differences between our runtime environment, since adding that file manually can fix my problem, it would be okay.
Thanks for this excellent project, it helps a lot and improved the coding experience.
