### ISSUE TITLE
关于lsp的问题

### ISSUE THREAD

**Issue by ToSeven** [Martins3/My-Linux-config#4]
我安装了neovim，我想问你你的自动补全插件是用的vim-lsp还是coc.nvim？coc.nvim不也有lsp功能吗？

**Comment by Martins3** [comment]
使用 coc.nvim 来实现 lsp 的功能，相关的配置在:
https://github.com/Martins3/My-Linux-config/blob/master/plugin/coc.vim

**Comment by Martins3** [comment]
自动补全实际上是具体的 language server 完成的，比如 ccls 用于 c/cpp 的补全，而 coc. nvim 的作用是将 ccls 发过来的消息接收过来，进行展示。

ls 可以做很多事情，比如静态检查，符号跳转，而补全只是其中的一种。

各种 ls 都是和 coc. nvim 通信的。

从我的了解来说，cco. nvim 比 vim-lsp 更好用，更强大。

**Comment by ToSeven** [comment]
好的，谢谢！
