### ISSUE TITLE
ccls - refs bug

### ISSUE THREAD

**Issue by UtopianFuture** [Martins3/My-Linux-Config#40]
- [ ] **Describe the bug**
the reference of ccls is wrong.
- [ ] **ccls --version**
the reference of ccls has a bug.

![image](https://user-images.githubusercontent.com/66514719/142730438-f1345f95-4309-46af-ba3f-18529e285720.png)

you can see, I think the first ref is about the reference of `pci_bus_devfn_reserved`, is 2, the second ref is about the reference of ` bus`, is 2, but we can see, the reference of `bus` is 1, and the third ref is about the reference of `devfn`, is 1
here is the reference of `pci_bus_devfn_reserved`

**Comment by UtopianFuture** [comment]
![image](https://user-images.githubusercontent.com/66514719/142730477-02cb1a8b-c391-4269-b09b-1910b76e19db.png)

**Comment by Martins3** [comment]
I know what you mean. Reference is managed by telescope-coc.nvim[^1], 

```vim
nmap <silent> <nowait> gr : <C-u>Telescope coc references<cr>
```
The difference between `coc-references` and `coc-references-used` is that latter one won't show the definition. In your example, it will not show `pci_bus_devfn_reserved`.
But telescope-coc.nvim doesn't provide option `coc-references-used` as provided by coc.vim[^2]

I will ask for the feature.

[^1]: https://github.com/fannheyward/telescope-coc.nvim
[^2]: https://github.com/neoclide/coc.nvim/blob/9f6e29b6f9661ebba10ff3df84de11d96c8a9e56/doc/coc.txt#L1275

**Comment by UtopianFuture** [comment]
ok.
first, thanks introduce the difference between `coc-references` and `coc-references-used`.
But I still have a question is that the second ref is about the reference of `bus`, is 2, but we can see, the reference of `bus` is 1
![image](https://user-images.githubusercontent.com/66514719/142746730-ade0b640-da44-435c-a057-22e22359980e.png)

**Comment by Martins3** [comment]
number 2 is not the references of `bus`, it's `devfn`.
the bug is caused by macro, there is a simpler example.
![Screenshot_2021-11-21_11-12-13](https://user-images.githubusercontent.com/16731244/142748024-e12b790f-9bca-426e-9360-3dd9db9058ec.png)
I will report this to coc.nvim or ccls.
