### ISSUE TITLE
E121: Undefined variable: vim

### ISSUE THREAD

**Issue by ebitgeek** [Martins3/My-Linux-Config#42]
系统: ubuntu21.10
NVIM v0.6.1
启动的时候提示了这个
![image](https://user-images.githubusercontent.com/48763080/148680614-433a2982-b04b-4849-b96d-0c79e2d5a6c4.png)

**Comment by Martins3** [comment]
据我所知，应该是没有 2.0.0-dev 的 neovim 吧[^1]

我需要更加详细的信息，具体参考
https://github.com/Martins3/My-Linux-Config/blob/master/.github/ISSUE_TEMPLATE/it-doesn-t-work-for-me.md

[^1]: https://github.com/neovim/neovim/releases

**Comment by ebitgeek** [comment]
> 据我所知，应该是没有 2.0.0-dev 的 neovim 吧[1](#user-content-fn-1-832b4379bfb38e745f1e83c9f00f1011)
> 
> 我需要更加详细的信息，具体参考 https://github.com/Martins3/My-Linux-Config/blob/master/.github/ISSUE_TEMPLATE/it-doesn-t-work-for-me.md
> 
> ## Footnotes
> 1. https://github.com/neovim/neovim/releases [↩](#user-content-fnref-1-832b4379bfb38e745f1e83c9f00f1011)

> 

Debian ccls version 0.20210330-1+b1
NVIM v0.6.1

我发尝试了下把这个插件注释掉 就没有这个提示了  不过我不太清楚这个插件是怎么引起这个错误的
![image](https://user-images.githubusercontent.com/48763080/148694681-a86b41c9-7bad-4f8a-a8c9-4733b48b210e.png)

这个插件重要吗 可以不使用吗

**Comment by Martins3** [comment]
这个插件的在这里 https://github.com/nvim-orgmode/orgmode ，这是一个用于帮助日程管理的插件，不重要。
