### ISSUE TITLE
`,S` 直接在工程中搜索当前光标所在字符

### ISSUE THREAD

**Issue by Datebasesystem** [Martins3/My-Linux-Config#44]
利用 telescope 快速搜索 file的时候，
`, o `可以在当前文件中间搜索该符号。

这里我提个小建议。可不可以用大写的O，来直接在当前文档中搜索当前光标所在的符号。因为每次用这个搜索都需要自己输入对应的符号，比较麻烦。

换成大写O直接搜索当前符号也可以和Spacevim之前的快捷键对应。因为我之前是spacevim用户，感觉直接用大写搜索当前光标所在字符非常方便。

同理， `, S `, `, F` 也可以安排一下 ：）

新年快乐！

**Comment by Martins3** [comment]
如果当前光标已经在该符号上了，为什么不使用 `g` `d` 直接跳转到定义

**Comment by Datebasesystem** [comment]
好像是这样的，哈哈
