### ISSUE TITLE
 filetree 中新建文件（文件夹）显示 Cannot make changes, 'modifiable' is off 

### ISSUE THREAD

**Issue by Datebasesystem** [Martins3/My-Linux-Config#47]
- [x] **Describe the bug**

文件树中，创建新文件的命令是a，创建文件夹的命令是A。但是这两个命令在我这里都没办法用。

都显示 Cannot make changes, 'modifiable' is off 。

我猜可能是把 filetree当成文本来识别了，a键映射的命令是插入，导致的这个问题。

![image](https://user-images.githubusercontent.com/37975634/152959952-5394e360-95e9-4a80-bb1d-d82388252908.png)

- [ NVIM v0.7.0-dev+963-g082ff2190 ] **nvim --version**
- [ linux ] **Operating System**

**Comment by Martins3** [comment]
你可以升级一下配置 https://martins3.github.io/My-Linux-Config/nvim.html#%E5%8D%87%E7%BA%A7 这个问题应该已经被修复了。
