### ISSUE TITLE
无 format 操作

### ISSUE THREAD

**Issue by TinyDolphin-Con** [Martins3/My-Linux-Config#48]
- [ ] **没有 format 选项（Space r f）**
<img width="478" alt="image" src="https://user-images.githubusercontent.com/35372742/153376164-3fa4a0a3-f1e7-4f33-a153-48c113db37aa.png">

- [ ] **clang version 13.0.1**
- [ ] **NVIM v0.7.0-dev+1048-gdba1df635**
- [ ] **MACOS 12.1 **
- [ ] **SPDebugInfo**
- [ ] **CocInfo**

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/35372742/153377282-8d9d25be-aa8a-4780-a684-0a3fa564e0bb.png">

- [ ] **checkhealth screenshot**
<img width="1853" alt="image" src="https://user-images.githubusercontent.com/35372742/153377527-2203e149-f76d-489f-995d-185c99f61def.png">

**Comment by Martins3** [comment]
不过，在 remove-spacevim 分支中，这个问题被修复了，你可以等一下，我会将那个分支合并到 master 上。

**Comment by TinyDolphin-Con** [comment]
> 不过，在 remove-spacevim 分支中，这个问题被修复了，你可以等一下，我会将那个分支合并到 master 上。

哈哈，自己加了映射， 新分支大概什么时候能合？（膜拜 ING）

**Comment by Martins3** [comment]
今天晚些时候应该可以吧，正在写 Dockerfile 和自动安装脚本，感觉我这个配置总体还是很简单的，但是对于新手而言，各种手动编译很麻烦。

**Comment by Martins3** [comment]
新的版本中，spacevim 将会被移除掉，整个配置会变的更加简单，如有任何疑惑，欢迎 issue.

**Comment by Martins3** [comment]
看来今天是搞不完了，在 docker 中注释的颜色不正常的:
![image](https://user-images.githubusercontent.com/16731244/153762095-b991fb8d-4b5f-4299-99ee-b82679ceee23.png)

正常的样子是这样的:
![image](https://user-images.githubusercontent.com/16731244/153762108-6636f50c-7ea6-4fea-a093-82e2f46062c9.png)

**Comment by TinyDolphin-Con** [comment]
> 看来今天是搞不完了，在 docker 中注释的颜色不正常的: ![image](https://user-images.githubusercontent.com/16731244/153762095-b991fb8d-4b5f-4299-99ee-b82679ceee23.png)
> 
> 正常的样子是这样的: ![image](https://user-images.githubusercontent.com/16731244/153762108-6636f50c-7ea6-4fea-a093-82e2f46062c9.png)

哈哈，辛苦大佬
