### ISSUE TITLE
Unable to install neovim config correctly

### ISSUE THREAD

**Issue by xiaoLeeFeiDao** [Martins3/My-Linux-Config#59]
Error detected while processing /home/stone/.dotfiles/init.vim:                              
line   73:                                                                                   
E5108: Error executing lua /home/stone/.config/nvim/lua/orgmode-config.lua:1: attempt to call
 field 'setup_ts_grammar' (a nil value)                                                      
stack traceback:                                                                             
        /home/stone/.config/nvim/lua/orgmode-config.lua:1: in main chunk                     
        [C]: in function 'require'                                                           
        [string ":lua"]:1: in main chunk                                                     
line   74:                                                                                   
E5108: Error executing lua .../start/telescope.nvim/lua/telescope/_extensions/init.lua:11: Th
is extension doesn't exist or is not installed: session-lens                                 
...escope/_extensions/session-lens/session-lens-library.lua:2: module 'auto-session' not foun
d:                                                                                           
        no field package.preload['auto-session']                                             
        no file './auto-session.lua'                                                         
        no file '/usr/share/luajit-2.1.0-beta3/auto-session.lua'                             
        no file '/usr/local/share/lua/5.1/auto-session.lua'                                  
        no file '/usr/local/share/lua/5.1/auto-session/init.lua'                             
        no file '/usr/share/lua/5.1/auto-session.lua'                                        
        no file '/usr/share/lua/5.1/auto-session/init.lua'                                   
        no file './auto-session.so'                                                          
        no file '/usr/local/lib/lua/5.1/auto-session.so'                                     
        no file '/usr/lib/lua/5.1/auto-session.so'                                           
        no file '/usr/local/lib/lua/5.1/loadall.so'                                          
stack traceback:                                                                             
        [C]: in function 'error'                                                             
        .../start/telescope.nvim/lua/telescope/_extensions/init.lua:11: in function '__index'
        .../start/telescope.nvim/lua/telescope/_extensions/init.lua:55: in function 'load_ext
ension'                                                                                      
        /home/stone/.config/nvim/lua/telescope-config.lua:51: in main chunk                  
        [C]: in function 'require'                                                           
        [string ":lua"]:1: in main chunk                                                     
line   75:                                                                                   
E5108: Error executing lua /home/stone/.config/nvim/lua/tree-config.lua:16: attempt to call f
ield 'setup' (a nil value)                                                                   
stack traceback:                                                                             
        /home/stone/.config/nvim/lua/tree-config.lua:16: in main chunk                       
        [C]: in function 'require'                                                           
        [string ":lua"]:1: in main chunk                                                     
line   77:                                                                                   
E5108: Error executing lua /home/stone/.config/nvim/lua/code-runner-config.lua:1: module 'cod
e_runner' not found:                                                                         
        no field package.preload['code_runner']
no file './code_runner.lua'                                                          
        no file '/usr/share/luajit-2.1.0-beta3/code_runner.lua'                              
        no file '/usr/local/share/lua/5.1/code_runner.lua'                                   
        no file '/usr/local/share/lua/5.1/code_runner/init.lua'                              
        no file '/usr/share/lua/5.1/code_runner.lua'                                         
        no file '/usr/share/lua/5.1/code_runner/init.lua'                                    
        no file './code_runner.so'                                                           
        no file '/usr/local/lib/lua/5.1/code_runner.so'                                      
        no file '/usr/lib/lua/5.1/code_runner.so'                                            
        no file '/usr/local/lib/lua/5.1/loadall.so'                                          
stack traceback:                                                                             
        [C]: in function 'require'                                                           
        /home/stone/.config/nvim/lua/code-runner-config.lua:1: in main chunk                 
        [C]: in function 'require'                                                           
        [string ":lua"]:1: in main chunk                                                     
Interrupted                                                                                  
Error detected while processing /usr/share/nvim/runtime/ftplugin.vim:                        
line    1:                                                                                   
Interrupted                                                                                  
Error detected while processing /usr/share/nvim/runtime/indent.vim:                          
line    1:                                                                                   
Interrupted                                                                                  
Error detected while processing CursorHold Autocommands for "*":                             
E117: Unknown function: CocActionAsync

**Comment by Martins3** [comment]
给我看看在 neovim 中执行命令 `PackerSync` 的截图

**Comment by Martins3** [comment]
出现这些报错应该是因为有些插件没有正确安装上

**Comment by xiaoLeeFeiDao** [comment]
我执行neovim的PackerSync之后，发现报错了，截图如下：
![image](https://user-images.githubusercontent.com/97346214/158271726-371e1f1a-f194-49b7-9ef1-ddcebf7357fd.png)

然后我尝试不断的使用R更新，最后剩下这七个插件无法更新了
![image](https://user-images.githubusercontent.com/97346214/158272097-45a6609a-5a93-4ff0-9882-a5731c506cfd.png)

**Comment by xiaoLeeFeiDao** [comment]
可以访问google和youguan,当前所有的插件已全部更新完成了
但是打开nvim时仍有报错，截图如下
![图片](https://user-images.githubusercontent.com/97346214/158380841-65934c38-08b0-4b42-a51b-98f70fb2e812.png)
gh命令找不着 这个是哪个工具，我google搜不到 
自己使用的是archlinux

**Comment by xiaoLeeFeiDao** [comment]
好的 我把orgmode-config和tree-config都注释后，初次打开nvim时已经不报错了，多谢指点
