### ISSUE TITLE
Previewer timed out, 是否可以配置超时时间呢?

### ISSUE THREAD

**Issue by sunashe** [Martins3/My-Linux-Config#61]
![image](https://user-images.githubusercontent.com/19219030/160244486-4663be06-c751-4068-9f80-e1fe39a04ef2.png)

**Comment by Martins3** [comment]
好问题，实际上，我也经常遇到这个情况，但是我没有仔细调查过。

这个 preview 是 telescope.nvim [^1] 提供的，在 vim 的 cmdline 中 `h telescope.nvim` 之后可以搜索到
```
          - timeout:          Timeout the previewer if the preview did not
                              complete within `timeout` milliseconds.
                              Set to false to not timeout preview.
                              Default: 250

```

[^1]: https://github.com/nvim-telescope/telescope.nvim

**Comment by Martins3** [comment]
顺便问一下，为什么你的名字是 艾希，但是头像是 奎因 :laughing:
