### ISSUE TITLE
[coc.nvim] Server languageserver.ccls failed to start

### ISSUE THREAD

**Issue by erhade** [Martins3/My-Linux-Config#63]
![Snipaste_2022-04-06_17-32-57](https://user-images.githubusercontent.com/49524292/161950287-f7cd85b0-a190-4b46-9a0f-34917aee50b1.png)
- [x] **[coc.nvim] Server languageserver.ccls failed to start: Error: invalid params of initialize: expected array for /workspaceFolders**
- [x] **ccls --version**0.20190823.6-1
- [x] **nvim --version**v0.7.0-dev+nightly
- [x] **Operating System**Ubuntu 64-bit Linux (v20.04.4 TLS).
- [x] **CocInfo**
![Snipaste_2022-04-06_17-57-01](https://user-images.githubusercontent.com/49524292/161950216-afd85838-0a31-4cbd-99e3-95db5e9e00d7.png)
- [x] **checkhealth screenshot**
![Snipaste_2022-04-06_18-02-13](https://user-images.githubusercontent.com/49524292/161950906-9ee17418-b764-4480-b15c-929d72d40366.png)
![Snipaste_2022-04-06_18-02-28](https://user-images.githubusercontent.com/49524292/161950938-64ade221-d8f7-4c33-8356-dd6a6abd6062.png)
![Snipaste_2022-04-06_18-02-36](https://user-images.githubusercontent.com/49524292/161950957-1e68d68f-b7dc-45ed-8bd4-304f281e5b77.png)

**Comment by Martins3** [comment]
I searched for the problem in Google and found several similar issues:
- https://github.com/neoclide/coc.nvim/issues/247
- https://stackoverflow.com/questions/68132335/server-languageserver-coc-clangd-failed-to-start-error-invalid-params-of-initi

I have to admit that I don't know the solution yet, but some suggestions may be considered helpful:
- update your ccls to the latest one
- fix the warnings in `checkhealth`
  -  Node.js provider
  - python3 provider
  - clipboard
