### ISSUE TITLE
f查询时，结果显示的时间过短

### ISSUE THREAD

**Issue by Datebasesystem** [Martins3/My-Linux-Config#64]
- What's your suggestion?

vim中按f查找时，会用a,b,c,d等字符显示出查找字母的位置。如图：
![image](https://user-images.githubusercontent.com/37975634/163519251-934bd5d7-33a9-4fdd-bedd-b9955e281b28.png)
这个功能是用什么插件实现的呢？我总感觉这个停留的时间太短了，手没那么快，每次都不能准确地跳转到我想要的位置。

- Why is better?

能不能自定义查询结果停留的时间？可以延长一些。

- How to implement your ideas?

**Comment by Martins3** [comment]
这是 [coc-smartf](https://github.com/neoclide/coc-smartf) 实现的，可以设置，具体参考其文档。

**Comment by Datebasesystem** [comment]
牛🍺！改好了。找了半天没找到。
