### ISSUE TITLE
新版本目录树的变动不太适应

### ISSUE THREAD

**Issue by a674709300** [Martins3/My-Linux-Config#68]
升级了新的全版本后，使用中感觉下面这个用着不太适应。
目录树在打开状态的时候，关闭 buffer，会导致目录树直接占据全屏,需要重新打开才能恢复到只占据左侧的大小，希望在关闭一个 buffer 的并且还有其他 buffer 的时候，能让主窗口转到下一个 buffer，然后目录树的窗口保持原本大小。

最后还有个就是，新版本在本地的使用是正常的，但是在在使用 windTerm 远程连接的时候使用，会出现这样的问题，已经尝试了好几种字体，一些字体的情况会好很多，但是在一些情况下依然还是会出现，老版本的时候则没有遇到过。
![图片](https://user-images.githubusercontent.com/13486247/164913931-f1bd8603-a71e-4590-93a4-ea4c27399da9.png)

**Comment by Martins3** [comment]
> 目录树在打开状态的时候，关闭 buffer，会导致目录树直接占据全屏,需要重新打开才能恢复到只占据左侧的大小，希望在关闭一个 buffer 的并且还有其他 buffer 的时候，能让主窗口转到下一个 buffer，然后目录树的窗口保持原本大小。

因为现在修改了文件树为 nvim-tree, 我会调查一下能否实现这个功能。

> 最后还有个就是，新版本在本地的使用是正常的，但是在在使用 windTerm 远程连接的时候使用，会出现这样的问题，已经尝试了好几种字体，一些字体的情况会好很多，但是在一些情况下依然还是会出现，老版本的时候则没有遇到过。

我会尝试复现一下 windTerm 下的工作情况

**Comment by a674709300** [comment]
非常感谢

**Comment by Martins3** [comment]
> 非常感谢

非常抱歉，最近在赶 deadline ，我会在 5 月 1 之前来解决一下这个问题。

**Comment by Martins3** [comment]
> 希望在关闭一个 buffer 的并且还有其他 buffer 的时候，能让主窗口转到下一个 buffer，然后目录树的窗口保持原本大小。

https://github.com/kyazdani42/nvim-tree.lua 的 readme 中提到了:
> You can automatically close the tab/vim when nvim-tree is the last window in the tab. WARNING: other plugins or automation 
may interfere with this:
> ```vim
> autocmd BufEnter * ++nested if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif
> ```

**Comment by Martins3** [comment]
windTerm  重新开一个 issue 讨论吧，一个问题一个  issue 会好一点。

**Comment by Martins3** [comment]
我放到了 #69 中间。
