### ISSUE TITLE
Blank line in WindTerm

### ISSUE THREAD

**Issue by Martins3** [Martins3/My-Linux-Config#69]
Originally motioned in #68, But I think a separate issue is better, below it's the solution:

see issue https://github.com/kingToolbox/WindTerm/issues/59 to change the fonts:
change 
```
{
	"name": "text.default",
	"style": {
		"foreground": "#F8F8F2",
		"background": "#1c1c1c",
		"fontFamily": "Roboto Mono, Fira Code Retina, Lucida Sans Typewriter, Lucida Console, Monoca",
		"fontSize": 10
	}
}
```
to 
```
		{
			"name": "text.default",
			"style": {
				"foreground": "#F8F8F2",
				"background": "#1c1c1c",
				"fontFamily": "Hasklug Nerd Font",
				"fontSize": 11
			}
		},
```
Then the problem fixed:
![image](https://user-images.githubusercontent.com/16731244/165888440-8ce54e96-27e4-4133-92bc-44da6bbc36ec.png)

**Comment by a674709300** [comment]
这个还是不行，主要应该是因为符号和中文的宽度不一样导致的。Hasklug Nerd Font 这个字体在没有中文的时候是基本正常的，但是有中文了就不行了。我现在用的是大小为10（其他大小也会有问题）的更纱黑体，这个是一个中文对应两个英文的宽度，所以会好很多，但是还有有些符号的显示会出问题。
![image](https://user-images.githubusercontent.com/13486247/165894929-ca2b8d3a-85d7-4b01-8fca-121447442006.png)
下面是更纱黑体的
![image](https://user-images.githubusercontent.com/13486247/165895092-c9311446-61d5-4cfb-b88f-c72f9e035cf4.png)
但是更纱黑体在这个情况下也还是会有点小问题
![image](https://user-images.githubusercontent.com/13486247/165895198-e987c458-b91a-4d84-8587-7e7853d68ad1.png)

**Comment by a674709300** [comment]
主要以前那个版本我记得也换了  nvim-tree 吧，那个用着我记得好像是没有这个问题。_(:зゝ∠)_

**Comment by Martins3** [comment]
那个版本，是基于 SpaceVim 的版本吗?

**Comment by a674709300** [comment]
是的，还是基于 SpaceVim 的那个版本

**Comment by a674709300** [comment]
不过换更纱黑体后，大部分情况下都基本可以使用了，目前在10号大小下，目前遇到的，除了上面那个符号的问题外，就只有这里这个了：
![image](https://user-images.githubusercontent.com/13486247/165897894-a6500c29-bfde-4e5e-b3fb-1febeabb5475.png)

**Comment by a674709300** [comment]
> 不过换更纱黑体后，大部分情况下都基本可以使用了，目前在10号大小下，目前遇到的，除了上面那个符号的问题外，就只有这里这个了： ![image](https://user-images.githubusercontent.com/13486247/165897894-a6500c29-bfde-4e5e-b3fb-1febeabb5475.png)

这个换行找到解决方案了，把 WindTerm 的自动换行关了就好了：
![image](https://user-images.githubusercontent.com/13486247/165898548-f9398c97-4217-45f4-baaa-f159ee69f778.png)

**Comment by Martins3** [comment]
所以问题解决了 ?

**Comment by a674709300** [comment]
算是把，基本大部分情况下都可以正常使用了，还剩的那个小问题，也不影响使用，只是看起来有点碍眼

**Comment by a674709300** [comment]
> 

要解决，或许可以通过换个符号来搞定，不用它那个三角感叹号，后面我自己再试下

**Comment by Martins3** [comment]
顺便问一下，为什么不尝试 tmux ?

**Comment by a674709300** [comment]
没用过 tmux ，这个不是 ssh 工具吧。是指在远程 linux 上安装  tmux 后，连上后通过 tmux 来开启会话使用吗。

**Comment by a674709300** [comment]
> 没用过 tmux ，这个不是 ssh 工具吧。是指在远程 linux 上安装 tmux 后，连上后通过 tmux 来开启会话使用吗。

我会试下的，谢谢。

**Comment by Martins3** [comment]
> 没用过 tmux ，这个不是 ssh 工具吧。是指在远程 linux 上安装 tmux 后，连上后通过 tmux 来开启会话使用吗。

是的
