### ISSUE TITLE
您好，我这边是个新手，请问一下，我配置好环境后，一直出现python 的错误，还有 defx的错误

### ISSUE THREAD

**Issue by weihongkai2008** [Martins3/My-Linux-config#7]
已经搭建两天了，还是各种问题，在 debian 9 和 mac上都在尝试搭建，但是或多或少还是出问题，
![Screen Shot 2020-11-04 at 00 03 58](https://user-images.githubusercontent.com/10654107/98010117-4bddf400-1e31-11eb-89fd-c0dc9cf5802a.png)

**Comment by weihongkai2008** [comment]
![Screen Shot 2020-11-04 at 00 05 12](https://user-images.githubusercontent.com/10654107/98010235-6adc8600-1e31-11eb-85bd-1762186658a8.png)
![Screen Shot 2020-11-04 at 00 05 50](https://user-images.githubusercontent.com/10654107/98010325-82b40a00-1e31-11eb-9aa4-888703c71867.png)

**Comment by Martins3** [comment]
你可以给我看看分别执行:
1. checkhealth
2. SPUpdate
的结果吗 ?

**Comment by Martins3** [comment]
一般是因为潜在的依赖没有安装

**Comment by weihongkai2008** [comment]
![截屏2020-11-04 22 19 48](https://user-images.githubusercontent.com/10654107/98123319-aa1bdd00-1eec-11eb-9628-d3b2caec4623.png)

**Comment by Martins3** [comment]
安装这个依赖:
```sh
pip3 install neovim
```
