### ISSUE TITLE
gnome.conf这个配置怎么导入和导出呢

### ISSUE THREAD

**Issue by wqk151** [Martins3/My-Linux-Config#72]
请问下，这个是gnome terminal的配置吗，这个怎么导入和导出配置呢，谢谢！

**Comment by Martins3** [comment]
参考这个 : https://unix.stackexchange.com/questions/448811/how-to-export-a-gnome-terminal-profile

**Comment by Martins3** [comment]
我已经不使用 gnome-terminal 了，目前我现在的感觉而言， kitty [^1] 是最好用的。

[^1]: https://sw.kovidgoyal.net/kitty/

**Comment by wqk151** [comment]
谢谢，我也试试kitty，感谢
