### ISSUE TITLE
执行packerUpdate或packersync后，自动补全的tab或enter不能用了

### ISSUE THREAD

**Issue by marryton007** [Martins3/My-Linux-Config#77]
环境：
Ubuntu 20.04

```shell
~/.config/nvim master !5 ❯ nvim -v                                                                                                                                        5m 27s jiaxi@lenovo
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by jiaxi@lenovo

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

使用你最新配置，执行packerUpdate或packerSync之后，再打开nvim时会出现提示

![image](https://user-images.githubusercontent.com/2311328/183861684-091a0e79-d2ad-4e3b-85e1-7ae6787cd377.png)

在写代码时，不论按tab或enter键，都不能自动补全了。

**Comment by Martins3** [comment]
类似的 https://github.com/Martins3/My-Linux-Config/issues/76

看来的确是有问题，我今晚看看

**Comment by Martins3** [comment]
同步了 coc.nvim 的配置，问题修复了，可以关联的 commit，不过这里存在一个小的改动，现在是 enter 选择补全，以前是 tab 的，我将这个分支合并到 master 上，你可以更新尝试一下。

**Comment by marryton007** [comment]
it works fine.

**Comment by marryton007** [comment]
还是比较喜欢原来tab补全的方式，特别是tab还可以提示函数输入下1个参数。

**Comment by Martins3** [comment]
习惯一下吧，还是和上游保持一致吧
