### ISSUE TITLE
A tiny descriptive bug

### ISSUE THREAD

**Issue by lan9786123** [Martins3/My-Linux-Config#79]
https://github.com/Martins3/My-Linux-Config/tree/master/docs/nvim.md

FAQ

    为什么不使用 VSCode ?

    VSCode 比 Sublime 功能更强，比 [Atom](https://atom.io/) 性能更高，而且 VSCode 内部是可以继承 vim 的。VSCode 因为是基于 electron 的，甚至可以在一个 window 编辑 markdown, 一个 window 实时预览 markdown 。但是 vim 可以更加简洁, 灵活和高效。
    VSCode 的功能非常强大，几乎发
    ----------------------^

There may be some other descriptions here. ^_^

**Comment by Martins3** [comment]
Thanks
