### ISSUE TITLE
切换到init.lua

### ISSUE THREAD

**Issue by wqk151** [Martins3/My-Linux-Config#81]
什么时候切换到init.lua啊，都是纯lua插件，感觉比vim的性能要高很多。

**Comment by Martins3** [comment]
我觉得你的这个建议很好，实际上，我在去年的时候就有这个计划（ #15 ）。将配置替换为 vim 配置替换为 lua 有很多好处，至少新用户没有必要同时学习两套配置语言。但是我认为这个事情对于我来说是一件不重要且不紧急的，因为现在的配置完全够用，换成 lua 配置不会带来更多的功能和便捷，但是需要对于很多位置进行调整，例如 init.vim 和 misc.vim 。与其将实际上浪费在这些地方，不如去做些更加有趣的事情，例如学习 Linux 内核，乱序多发射 CPU 以及 LLVM 。

如果你还是感觉有必要，可以看看一下两篇文章:
- https://fann.im/blog/2021/08/01/thoughts-on-coc.nvim/
- https://calebschoepp.com/blog/2022/productivity-porn/
