### ISSUE TITLE
分屏问题

### ISSUE THREAD

**Issue by Datebasesystem** [Martins3/My-Linux-Config#86]
![image](https://user-images.githubusercontent.com/37975634/196855797-e8ebfd04-eeff-4b28-945e-472043271510.png)
大佬，为啥我的coc查找的分屏都是水平分的呢？有没有什么办法改成垂直分的，类似于：
![image](https://user-images.githubusercontent.com/37975634/196855931-141bfa41-61e9-4da6-9ad9-e807ff3b0d28.png)
像例子中那样。
求指导！非常感谢！

**Comment by Martins3** [comment]
这个是通过 telescope-config.lua 来控制的，将其中的 `    layout_strategy = "vertical",` 删除就可以了，coc 是提供数据，telescope 来实现数据搜索，telescope 的可以定制样式。具体可以参考 https://github.com/nvim-telescope/telescope.nvim

**Comment by Datebasesystem** [comment]
可以了，感谢大佬。我研究研究！
