### ISSUE TITLE
plugin里修改了配置，未生效

### ISSUE THREAD

**Issue by Yihen** [Martins3/My-Linux-config#9]
- **Describe the bug**
我clone了您的repo，并在plugin下增加了一些配置，配置却并没有生效；其他的地方都没有改动；请问这是为什么呢？
- **ccls --version**
10.0.1
- **nvim --version**
v0.4.4
- **checkhealth screenshot**
NO ERROR

**Comment by Martins3** [comment]
你在哪一个位置加的插件，可以把 diff 给我看看吗 ?

**Comment by Yihen** [comment]
@Martins3 抱歉，是我看错了；没有问题的；感谢您的repo
