### ISSUE TITLE
some strange chars show in c source file.

### ISSUE THREAD

**Issue by marryton007** [Martins3/My-Linux-Config#99]
最新代码，打开一个C源文件，里面多出一些奇怪的东西，见图中红笔圈出的内容。如何去掉这些东西 ？

![image](https://user-images.githubusercontent.com/2311328/201911805-3eb28023-4d5d-4205-a6c1-b542eefeeed9.png)

**Comment by marryton007** [comment]
add the follow lines to the coc-settings.json
```sh
"inlayHint.enable": false
```

**Comment by Martins3** [comment]
Nice suggestion, I'll merge this.

**Comment by Martins3** [comment]
you can open a pull request
